language: ruby
rvm:
- 2.3.0
addons:
  code_climate:
    repo_token:
      secure: SZWq5GxdndVN/xOfX85gBNk1hXk1O60PlhWDaTP8nCN9qz4SvTEuTxTehcd8lfAJoY2BzU8C6dj3oJS4sCG591yTpIGuoDymodUxefK77kictrDLtZJqQ5LJY9qvbq2RelI48zPNiwm5QHV22iWFuu5UVqAHjYTz2cG+inWhDFmkRX2KbOuvcsMNxiED/2kJBo7LA/fGERHwNSnQp2zINyxTcoZsFkaMMeNhhygq5nNNAZKXOISQ44dbNZWscVuy6XQCP3y0FS1x/2eOnl0RksIAVqyRa70FaVB0x8TVSRwQXgHVntxhw3/mxprWo7VA8RBI4hyhq10JAWHiASjXqWhU24sl6kg1mRoqUG1fr77ZsnlJbbVARu3lJbRuOExybSio2MTNterfCUjzNdevOrh+eLIaLJK0gEDy2e+ok79x0GSYtVmTJtMjaXJH7fFdENamfATJFJ9OYkr60mFv76QXB7ZqfW0nWVNs0H0guydAxawhq9LokyhOdHTeDq5p6dDAP7V98VKZcQ2nQGuboAxr10gl1BzH1SkEvM66nwyoKuoxgDgilIuIlBz0F7oIKSby8p/aBNjaS0MSrKmIA7bC9CkD6SjOkVCkNkECeGjkEWEot/+PxeAtGts0LxugxyJcyuuJMAlnOjn0k+cZ1UcV5r0SUpiXkoHgJUDbjF0=
