# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a1f28ba55ba03bc9b8be6fb814f5fa487defc6dcfc9a1878731d26ad123aa2942e2fc86d54a242be52a9b31c9f51744307e078476e04eec39882777a52f616e

test:
  secret_key_base: 0bab3ce32842972b9f77c1391a3e28678afe523fb9ba14cf0cbfadc71ea3d4e70e33d2c14683bef44166ed39d7eee8ba3fb2c3c81b0d91cd54be92179922e353

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
